on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    if: github.repository == 'tobilg/duckdb-tileserver'
    steps:

    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build ARM64
      run: make TARGETARCH=arm64 multi-stage-docker

    - name: Build x86_64
      run: make TARGETARCH=amd64 multi-stage-docker

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Upload
      env:
        DOCKER_REPO: tobilg/duckdb-tileserver
      run: |
        docker push --all-tags $DOCKER_REPO
        docker manifest create $DOCKER_REPO:latest $DOCKER_REPO:latest-amd64 $DOCKER_REPO:latest-arm64
        docker manifest push $DOCKER_REPO:latest
        date_tag=$(docker images | grep tileserver | grep -v latest | grep -v arm64 | awk '{print $2}')
        date_tag=${date_tag/-amd64/}
        docker manifest create $DOCKER_REPO:${date_tag} $DOCKER_REPO:${date_tag}-amd64 $DOCKER_REPO:${date_tag}-arm64
        docker manifest push $DOCKER_REPO:${date_tag}
